setlocal

set APPVEYOR_REPO_TAG=True
set APPVEYOR_BUILD_VERSION=0.1.0
set APPVEYOR_REPO_COMMIT_AUTHOR=pchalamet
set APPVEYOR_REPO_COMMIT_MESSAGE=test %APPVEYOR_BUILD_VERSION%
set APPVEYOR_PROJECT_NAME=full-build
set PLATFORM=Any CPU
set CONFIGURATION=Release

rem NOTE: GITHUB_TOKE must be set
rem set GITHUB_TOKEN=

call ../push-release.bat

endlocal
